---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - telegraf
        - mtr
        - nmap

    - name: Enable and start telegraf
      service:
        name: telegraf
        state: started
        enabled: yes

    - name: Enable and start mtr service
      service:
        name: mtr
        state: started
        enabled: yes

    - name: Enable and start nmap service
      service:
        name: nmap
        state: started
        enabled: yes
