---
- hosts: managementservers 
  become: yes
  tasks:
  - name: Install haproxy
    apt:
      name:
      - haproxy
      state: latest
      update_cache: yes

   - name: Enable and start haproxy
      service:
        name: haproxy
        state: started
        enabled: yes   

   - name: Update configuration file
     template:
       src: template/haproxy.cfg
       dest: /etc/haproxy/haproxy.cfg
     notify:  restart haproxy

  handlers:  
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

  


    
